version: '3.8'
services:
  app:
    image: node:bullseye-slim
    ports: 
      - 3000:3000
    volumes:
      - .:/home/node/app
    working_dir: /app 
    command: bash -c "npm install && npm start"
    depends_on:
      - postgres
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
    - ./postgres/data:/var/lib/postgresql/data
    - ./postgres/scripts/:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=postgres
      - POSTGRES_ROOT_PASSWORD=root
      - POSTGRES_DB=app